// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (id, user_id, filename, mime_type, size, folder, storage_path) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateFileParams struct {
	ID          string
	UserID      string
	Filename    string
	MimeType    string
	Size        int64
	Folder      string
	StoragePath string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.ExecContext(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.Folder,
		arg.StoragePath,
	)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, filename, mime_type, size, folder, storage_path, created_at, last_accessed FROM files WHERE id = ?
`

type GetFileByIDRow struct {
	ID           string
	UserID       string
	Filename     string
	MimeType     string
	Size         int64
	Folder       string
	StoragePath  string
	CreatedAt    sql.NullTime
	LastAccessed sql.NullTime
}

func (q *Queries) GetFileByID(ctx context.Context, id string) (GetFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i GetFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Folder,
		&i.StoragePath,
		&i.CreatedAt,
		&i.LastAccessed,
	)
	return i, err
}

const getUserStorageUsage = `-- name: GetUserStorageUsage :one
SELECT COALESCE(SUM(size), 0) FROM files WHERE user_id = ?
`

func (q *Queries) GetUserStorageUsage(ctx context.Context, userID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUserStorageUsage, userID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listFilesByUser = `-- name: ListFilesByUser :many
SELECT id, user_id, filename, mime_type, size, folder, storage_path, created_at, last_accessed FROM files WHERE user_id = ? ORDER BY created_at DESC
`

type ListFilesByUserRow struct {
	ID           string
	UserID       string
	Filename     string
	MimeType     string
	Size         int64
	Folder       string
	StoragePath  string
	CreatedAt    sql.NullTime
	LastAccessed sql.NullTime
}

func (q *Queries) ListFilesByUser(ctx context.Context, userID string) ([]ListFilesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesByUserRow
	for rows.Next() {
		var i ListFilesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Folder,
			&i.StoragePath,
			&i.CreatedAt,
			&i.LastAccessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMimeTypesByUser = `-- name: ListMimeTypesByUser :many
SELECT mime_type FROM files WHERE user_id = ?
`

func (q *Queries) ListMimeTypesByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMimeTypesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mime_type string
		if err := rows.Scan(&mime_type); err != nil {
			return nil, err
		}
		items = append(items, mime_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentUploads = `-- name: ListRecentUploads :many
SELECT id, user_id, filename, mime_type, size, folder, storage_path, created_at, last_accessed FROM files WHERE user_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListRecentUploadsParams struct {
	UserID string
	Limit  int64
}

type ListRecentUploadsRow struct {
	ID           string
	UserID       string
	Filename     string
	MimeType     string
	Size         int64
	Folder       string
	StoragePath  string
	CreatedAt    sql.NullTime
	LastAccessed sql.NullTime
}

func (q *Queries) ListRecentUploads(ctx context.Context, arg ListRecentUploadsParams) ([]ListRecentUploadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentUploads, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentUploadsRow
	for rows.Next() {
		var i ListRecentUploadsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Folder,
			&i.StoragePath,
			&i.CreatedAt,
			&i.LastAccessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentlyPlayed = `-- name: ListRecentlyPlayed :many
SELECT id, user_id, filename, mime_type, size, folder, storage_path, created_at, last_accessed FROM files WHERE user_id = ? AND last_accessed IS NOT NULL ORDER BY last_accessed DESC LIMIT ?
`

type ListRecentlyPlayedParams struct {
	UserID string
	Limit  int64
}

type ListRecentlyPlayedRow struct {
	ID           string
	UserID       string
	Filename     string
	MimeType     string
	Size         int64
	Folder       string
	StoragePath  string
	CreatedAt    sql.NullTime
	LastAccessed sql.NullTime
}

func (q *Queries) ListRecentlyPlayed(ctx context.Context, arg ListRecentlyPlayedParams) ([]ListRecentlyPlayedRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentlyPlayed, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentlyPlayedRow
	for rows.Next() {
		var i ListRecentlyPlayedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Folder,
			&i.StoragePath,
			&i.CreatedAt,
			&i.LastAccessed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileFolder = `-- name: UpdateFileFolder :exec
UPDATE files SET folder = ? WHERE id = ?
`

type UpdateFileFolderParams struct {
	Folder string
	ID     string
}

func (q *Queries) UpdateFileFolder(ctx context.Context, arg UpdateFileFolderParams) error {
	_, err := q.db.ExecContext(ctx, updateFileFolder, arg.Folder, arg.ID)
	return err
}

const updateFileSize = `-- name: UpdateFileSize :exec
UPDATE files
    SET size = ?
    WHERE id = ?
`

type UpdateFileSizeParams struct {
	Size int64
	ID   string
}

func (q *Queries) UpdateFileSize(ctx context.Context, arg UpdateFileSizeParams) error {
	_, err := q.db.ExecContext(ctx, updateFileSize, arg.Size, arg.ID)
	return err
}

const updateFilename = `-- name: UpdateFilename :exec
UPDATE files SET filename = ? WHERE id = ?
`

type UpdateFilenameParams struct {
	Filename string
	ID       string
}

func (q *Queries) UpdateFilename(ctx context.Context, arg UpdateFilenameParams) error {
	_, err := q.db.ExecContext(ctx, updateFilename, arg.Filename, arg.ID)
	return err
}

const updateLastAccessed = `-- name: UpdateLastAccessed :exec
UPDATE files SET last_accessed = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateLastAccessed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateLastAccessed, id)
	return err
}
