// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (id, file_id, task_type, status) VALUES (?, ?, ?, 'pending')
`

type CreateJobParams struct {
	ID       string
	FileID   string
	TaskType string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob, arg.ID, arg.FileID, arg.TaskType)
	return err
}

const getPendingOrProcessingJobs = `-- name: GetPendingOrProcessingJobs :many
SELECT id, file_id, task_type, status, COALESCE(error, '') FROM jobs WHERE status IN ('pending', 'processing')
`

type GetPendingOrProcessingJobsRow struct {
	ID       string
	FileID   string
	TaskType string
	Status   string
	Error    string
}

func (q *Queries) GetPendingOrProcessingJobs(ctx context.Context) ([]GetPendingOrProcessingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOrProcessingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingOrProcessingJobsRow
	for rows.Next() {
		var i GetPendingOrProcessingJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.TaskType,
			&i.Status,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs SET status = ?, error = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status string
	Error  sql.NullString
	ID     string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.Status, arg.Error, arg.ID)
	return err
}
