// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type File struct {
	ID               string
	UserID           string
	Filename         string
	MimeType         string
	Size             int64
	Folder           string
	StoragePath      string
	LastAccessed     sql.NullTime
	CreatedAt        sql.NullTime
	DeletedAt        sql.NullTime
	PlaybackProgress sql.NullInt64
}

type Folder struct {
	ID        string
	UserID    string
	Path      string
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
}

type Job struct {
	ID        string
	FileID    sql.NullString
	TaskType  string
	Status    string
	Progress  int64
	Error     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    sql.NullString
}

type RefreshToken struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt time.Time
	Revoked   bool
	CreatedAt sql.NullTime
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
