// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type File struct {
	ID           string
	UserID       string
	Filename     string
	MimeType     string
	Size         int64
	Folder       string
	StoragePath  string
	LastAccessed sql.NullTime
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type Folder struct {
	ID        string
	UserID    string
	Path      string
	DeletedAt sql.NullTime
	CreatedAt sql.NullTime
}

type Job struct {
	ID        string
	FileID    string
	TaskType  string
	Status    string
	Error     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RefreshToken struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt time.Time
	Revoked   bool
	CreatedAt sql.NullTime
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}
